#!/bin/bash

#PBS -l nodes=3:ppn=20,mem=700GB
#PBS -l walltime=100:00:00
#PBS -N Mr19-3
#PBS -M mv1003@nyu.edu,mohammadjavad.vakili@gmail.com
#PBS -m abe
#PBS -j oe

module purge
module load mpi4py/openmpi/intel/1.3.1
module load numpy/intel/1.10.1
module load corrfunc/intel/1.0.0

cd /scratch/mv1003/projects/gambley3/gambly/run

mpiexec -np 60 python /scratch/mv1003/projects/gambley3/gambly/code/mcmc.py 140 500000 19.

# leave a blank line at the end

