#!/bin/bash

#PBS -l nodes=1:ppn=2,mem=10GB
#PBS -l walltime=2:00:00
#PBS -N Mr20_new
#PBS -M mv1003@nyu.edu,mohammadjavad.vakili@gmail.com
#PBS -m abe
#PBS -j oe

module purge
module load mpi4py/openmpi/intel/1.3.1
module load numpy/intel/1.10.1
module load corrfunc/intel/1.0.0
module load fast3tree/intel/20151009
cd /scratch/mv1003/projects/gambly/run

mpiexec -np 2 python /scratch/mv1003/projects/gambly/code/mcmc.py 10 10000 20.

# leave a blank line at the end

